### ISSUE TITLE
chat ui

### ISSUE THREAD

**Issue by hrxorxm** [KiYOUNG2/front-end#3]
## TODO
- [x]  말풍선 크기 조절
- [x]  팝업창에서 이미지 업로드시 채팅창에 띄우기
- [x]  초기 메세지 설정
- [x]  이미지 클릭 시 확대
- [x]  대화창 크기고정 및 스크롤
- [x]  채팅창 프로필 변경
- [x]  답변 채팅 사이 딜레이 추가
- [x]  채팅창 입력 시 제일 아래를 가리키도록 수정
- [x]  말풍선 크기 및 색깔 지정
- [x]  메세지 폰트 등 스타일 적용
