### ISSUE TITLE
main ui

### ISSUE THREAD

**Issue by hrxorxm** [KiYOUNG2/front-end#4]
## TODO
- [x]  전체적인 디자인 통일하기
- [x]  페이지 제목 바꾸기
- [x]  기영이 로고 사진 넣기
- [x]  About 페이지 만들기
